import type { Metadata } from 'next'
import { Quicksand as FontSans } from 'next/font/google'
import './globals.css'
import { cn } from '@/lib/utils'
import { TailwindIndicator } from '@/components/tailwind-indicator'
import Footer from '@/components/footer'
import { ThemeProvider } from '@/components/theme-provider'

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={cn('antialiased font-sans', fontSans.variable)}>
        <ThemeProvider attribute='class' defaultTheme='dark' enableSystem>
          <main className='min-h-screen bg-background font-sans '>
            {children}
          </main>
          <Footer />
          <TailwindIndicator />
        </ThemeProvider>
      </body>
    </html>
  )
}
